services:
  app:
    build:
      context: .
      args:
        - DEV=true  # Build from the current directory
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    volumes:
      - ./app:/app  # Mount the app directory to /app in the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
